# We use poetry to run formatting and linting before commit/push
# Longer checks such as tests, security and complexity baseline
# are run as part of CI to prevent slower feedback loop
# All checks can be run locally via `make pr`

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-merge-conflict
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-toml
          - id: debug-statements
          - id: detect-private-key
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
          - id: mixed-line-ending
    - repo: local
      hooks:
          - id: black
            name: formatting::black
            entry: poetry run black
            language: system
            types: [python]
    - repo: local
      hooks:
          - id: isort
            name: formatting::isort
            entry: poetry run isort
            language: system
            types: [python]
    # - repo: local
    #   hooks:
    #       - id: ssort
    #         name: formatting::ssort
    #         entry: poetry run ssort
    #         language: system
    #         types: [python]
